### ISSUE TITLE
 extracte  Twitter's data 

### ISSUE THREAD

**Issue by kelly329** [RodolfoFerro/pandas_twitter#1]
Hi,Thanks for the tutorial. I am interested in it.
I am getting error when I am trying to train the model.
An error occurred while  extracting  Twitter's data 
Below is the error.
<img width="924" alt="2018-03-26 14 44 52" src="https://user-images.githubusercontent.com/20393368/37891600-64deae82-3107-11e8-83d0-5f19b91369eb.png">

I think the problem is that I don’t know how to use the parameters in the credentials.py
Personally, i think the consumer key is my personal twitter account and the consumer secert is my account password ,but I do not know how to get access_token and Access Token Secret

Thank you very much!

**Comment by kelly329** [comment]
Hello! I'm not sure whether you notice my issue. I'm looking forward your reply. Thank you for reading this. :)

**Comment by GuillermoYanez** [comment]
@kelly329  Hi! First, you need to create a Twitter App at https://apps.twitter.com. once you've created an App (your Twitter account must be verified), go to 'Keys and Access Kokens' tab. Necessary data (consumer key, access token, etc) are placed in it. :)

**Comment by kelly329** [comment]
@GuillermoYanez Hi, Thank you so much.  My problem has been solved.
